contact_links:
  - name: Want our help? 🤝
    url: https://thatopen.com/accelerator
    about: Are you developing a project with our technology and would like our help? Apply now to join That Open Accelerator Program!
  - name: Community
    url: https://people.thatopen.com/
    about: Join the community and discuss with other BIM software developers in real time.
